global:
    data_base_dir: /data
    group: deployuser1
    install_base_dir: /data/localization
    java_home: /data/jdk/
    jdk_path: /data/jdk
    pkg_pro_dir: /data/20251027-yuwq-cdtest
    software_dir: /data/softwares
    temp_dir: /data/tmp_install_dir
    timezone: Asia/Shanghai
    user: appuser
nodes:
    dw-master1:
        ip: 192.168.10.10
        hostname: dw-master1
    dw-master2:
        ip: 192.168.10.11
        hostname: dw-master2
    dw-master3:
        ip: 192.168.10.12
        hostname: dw-master3
    dw-worker1:
        ip: 192.168.10.13
        hostname: dw-worker1
    dw-worker2:
        ip: 192.168.10.14
        hostname: dw-worker2
    dw-worker3:
        ip: 192.168.10.15
        hostname: dw-worker3
    etl-ssdb:
        ip: 192.168.10.20
        hostname: etl-ssdb
    realtime-es1:
        ip: 192.168.10.16
        hostname: realtime-es1
    realtime-es2:
        ip: 192.168.10.17
        hostname: realtime-es2
    realtime-es3:
        ip: 192.168.10.18
        hostname: realtime-es3
    realtime-kafka1:
        ip: 192.168.10.13
        hostname: realtime-kafka1
    realtime-kafka2:
        ip: 192.168.10.14
        hostname: realtime-kafka2
    realtime-kafka3:
        ip: 192.168.10.15
        hostname: realtime-kafka3
    realtime-redis:
        ip: 192.168.10.19
        hostname: realtime-redis
serviceTop:
    docker:
        nodes:
            - dw-master3
            - dw-worker1
        id_auto_derive: false
    dolphinscheduler_api:
        nodes:
            - dw-master1
        id_auto_derive: false
    dolphinscheduler_master:
        nodes:
            - dw-master1
        id_auto_derive: false
    dolphinscheduler_worker:
        nodes:
            - dw-worker1
            - dw-worker2
            - dw-worker3
        id_auto_derive: false
    doris/be:
        nodes:
            - dw-master1
            - dw-worker1
            - dw-worker2
            - dw-worker3
        id_auto_derive: false
    doris/fe:
        nodes:
            - dw-master1
        id_auto_derive: false
    elasticsearch:
        nodes:
            - realtime-es1
            - realtime-es2
            - realtime-es3
        id_auto_derive: true
    flink_jobmanager:
        nodes:
            - dw-master1
        id_auto_derive: false
    flink_taskmanager:
        nodes:
            - dw-worker1
            - dw-worker2
            - dw-worker3
        id_auto_derive: false
    hadoop3:
        nodes:
            - dw-master1
            - dw-master2
            - dw-master3
            - dw-worker1
            - dw-worker2
            - dw-worker3
        id_auto_derive: false
    install_jdk:
        nodes:
            - '*'
        id_auto_derive: false
    kafka:
        nodes:
            - realtime-kafka1
            - realtime-kafka2
            - realtime-kafka3
        id_auto_derive: true
    mysql:
        nodes:
            - dw-master3
        id_auto_derive: false
    ntp_master:
        nodes:
            - dw-master1
        id_auto_derive: false
    ntp_slave:
        nodes:
            - dw-master2
            - dw-master3
            - dw-worker1
            - dw-worker2
            - dw-worker3
            - realtime-kafka1
            - realtime-kafka2
            - realtime-kafka3
            - realtime-es1
            - realtime-es2
            - realtime-es3
        id_auto_derive: false
    python3:
        nodes:
            - '*'
        id_auto_derive: false
    redis:
        nodes:
            - realtime-redis
        id_auto_derive: false
    scala:
        nodes:
            - dw-master1
            - dw-master2
            - dw-master3
            - dw-worker1
            - dw-worker2
            - dw-worker3
            - realtime-kafka1
            - realtime-kafka2
            - realtime-kafka3
        id_auto_derive: false
    server_init:
        nodes:
            - '*'
        id_auto_derive: false
    spark3:
        nodes:
            - '*'
        id_auto_derive: false
    ssdb:
        nodes:
            - etl-ssdb
        id_auto_derive: false
    test:
        nodes:
            - dw-master1
        id_auto_derive: false
    zookeeper:
        nodes:
            - dw-master1
            - dw-master2
            - dw-master3
        id_auto_derive: true
serverConfig:
    docker:
        type: ""
        description: ""
        id_field: ""
        id_format: ""
        vars:
            bin_path: /usr/local/bin
            package_subdir: realtime-new-doris/realtime/web_all/docker
    dolphinscheduler_api:
        type: ""
        description: ""
        id_field: ""
        id_format: ""
        vars:
            api_port: 12345
            version: 3.1.9
    dolphinscheduler_master:
        type: ""
        description: ""
        id_field: ""
        id_format: ""
        vars:
            master_port: 5678
            version: 3.1.9
    dolphinscheduler_worker:
        type: ""
        description: ""
        id_field: ""
        id_format: ""
        vars:
            version: 3.1.9
            worker_port: 1234
    doris/be:
        type: ""
        description: ""
        id_field: ""
        id_format: ""
        vars:
            be_port: 9060
            brpc_port: 8060
            data_subdir: apache-doris/be/storage
            heartbeat_service_port: 9050
            install_subdir: apache-doris/be
            version: 2.0.3
            webserver_port: 8040
    doris/fe:
        type: ""
        description: ""
        id_field: ""
        id_format: ""
        vars:
            data_subdir: apache-doris/fe/doris-meta
            edit_log_port: 9010
            http_port: 8030
            install_subdir: apache-doris/fe
            priority_networks: 192.168.10.0/24
            query_port: 9030
            rpc_port: 9020
            version: 2.0.3
    elasticsearch:
        type: ""
        description: Elasticsearch 分布式搜索和数据分析引擎
        id_field: ""
        id_format: ""
        vars:
            backup_subdir: elasticsearch/backup
            cluster_name: elasticsearch-cluster
            data_subdir: elasticsearch/data
            default_password: elasticsearch
            heap_size: ""
            http_port: "9200"
            install_subdir: elasticsearch
            jvm_heap_size: 4g
            log_subdir: elasticsearch/logs
            logrotate_max_size: 100M
            logrotate_retain_days: "14"
            node_data: "true"
            node_ingest: "true"
            node_master: "true"
            node_roles: ""
            package_subdir: elasticsearch
            package_url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.16.3-linux-x86_64.tar.gz
            rack_id: ""
            transport_port: "9300"
            version: 7.16.3
    flink_jobmanager:
        type: ""
        description: ""
        id_field: ""
        id_format: ""
        vars:
            rpc_port: 6123
            scala_version: "2.12"
            version: 1.18.0
            web_port: 8081
    flink_taskmanager:
        type: ""
        description: ""
        id_field: ""
        id_format: ""
        vars:
            memory: 2g
            task_slots: 4
            version: 1.18.0
    hadoop3:
        type: ""
        description: Hadoop 3 生态（HDFS HA + YARN HA）
        id_field: ""
        id_format: ""
        vars:
            blocksize: "268435456"
            datanode_data_port: 9866
            datanode_data_subdir: dfs/dn
            datanode_http_port: 9864
            install_subdir: hadoop
            journalnode_data_subdir: dfs/jn
            journalnode_port: 8485
            namenode_data_subdir: dfs/nn
            namenode_heapsize: 4096m
            namenode_http_port: 50070
            namenode_rpc_port: 8020
            nameservice: zhugeio
            nodemanager_local_subdir: hadoop3/hadoop-yarn/cache
            nodemanager_log_subdir: hadoop3/hadoop-yarn/containers
            nodemanager_resource_memory_mb: 12288
            package_subdir: realtime-new-doris/realtime/hadoop3
            pkg_name: hadoop-3.3.6.tar.gz
            remote_app_log_dir: hdfs://zhugeio/var/log/hadoop-yarn/apps
            resourcemanager_port: 8032
            resourcemanager_resource_port: 8031
            resourcemanager_scheduler_port: 8030
            resourcemanager_web_port: 8089
            scala_version: "2.12"
            scheduler_maximum_allocation_vcores: 8
            scheduler_minimum_allocation_mb: 32
            tmp_data_subdir: dfs/tmp
            version: 3.3.6
            vmem_pmem_ratio: 5
            yarn_cluster_id: zhugeio2
    install_jdk:
        type: global
        description: 安装JDK（所有节点）
        id_field: ""
        id_format: ""
        vars:
            package_subdir: realtime-new-doris/realtime/kafka
            pkg_name: jdk-8u202-linux-x64.tar.gz
    kafka:
        type: ""
        description: ""
        id_field: ""
        id_format: ""
        vars:
            consumer:
                group_id: test-consumer-group
                zookeeper_connection_timeout_ms: 6000
            install_subdir: kafka
            package_subdir: realtime-new-doris/realtime/kafka
            producer:
                acks: all
                batch_size: 16384
                buffer_memory: 3.3554432e+07
                retries: 3
            scala_version: "2.11"
            server:
                default_replication_factor: 2
                delete_topic_enable: true
                group_initial_rebalance_delay_ms: 0
                log_retention_check_interval_ms: 300000
                log_retention_hours: 168
                log_segment_bytes: 1.073741824e+09
                log_subdir: kafka-data
                num_io_threads: 8
                num_network_threads: 3
                num_partitions: 5
                offsets_topic_replication_factor: 1
                port: 9092
                socket_receive_buffer_bytes: 102400
                socket_request_max_bytes: 1.048576e+08
                socket_send_buffer_bytes: 102400
                transaction_state_log_min_isr: 1
                transaction_state_log_replication_factor: 1
                zookeeper_connection_timeout_ms: 6000
            topics:
                - name: sdklua_online
                  partitions: 5
                  replication_factor: 2
                - name: debug
                  partitions: 5
                  replication_factor: 2
                - name: pay_statisv2
                  partitions: 5
                  replication_factor: 2
                - name: pay_zg_total
                  partitions: 5
                  replication_factor: 2
                - name: pay_zg_total_random
                  partitions: 5
                  replication_factor: 2
                - name: tag-evaluate-new
                  partitions: 1
                  replication_factor: 1
                - name: file-task
                  partitions: 1
                  replication_factor: 1
                - name: group-user-load
                  partitions: 1
                  replication_factor: 1
            version: 2.11-0.11.0.2
            zookeeper:
                client_port: 2182
                data_subdir: zk-kafka-data
                election_port: 3889
                peer_port: 2889
    mysql:
        type: ""
        description: MySQL数据库（Docker部署）
        id_field: ""
        id_format: ""
        vars:
            container_name: zanalytics_mysql_v33
            container_port: 3306
            databases:
                - sdkv
                - audit_log
                - cep
            image_name: mysql-5.7.33.tar
            init_subdir: mysql/init
            mysql_config_subdir: mysql
            mysql_data_subdir: mysql/data
            mysql_database: sdkv
            mysql_host: realtime-db
            mysql_image: mysql:5.7.33
            mysql_password: zanalytics
            mysql_port: 3306
            mysql_root_password: zanalytics
            mysql_user: web
            package_subdir: realtime-new-doris/realtime/web_all/mysql
            sql_tools_subdir: tools
    ntp_master:
        type: ""
        description: NTP主服务器
        id_field: ""
        id_format: ""
        vars:
            stratum: 10
    ntp_slave:
        type: ""
        description: NTP从服务器
        id_field: ""
        id_format: ""
        vars: {}
    python3:
        type: global
        description: 安装Python3（所有节点）
        id_field: ""
        id_format: ""
        vars:
            package_subdir: realtime-new-doris/realtime/python3
            pkg_name: Python-3.6.8.tar.xz
            version: 3.6.8
            version_pip: "18.0"
            version_setuptools: 40.0.0
    redis:
        type: ""
        description: Redis缓存服务（编译安装，多实例）
        id_field: ""
        id_format: ""
        vars:
            appendfsync: everysec
            appendonly: "yes"
            bind: 0.0.0.0
            daemonize: "yes"
            databases: 16
            install_dir: /usr/local/redis
            instances:
                - data_subdir: redis_26480
                  logfile: redis_26480.log
                  pid_file: redis_26480.pid
                  port: 26480
                - data_subdir: redis_26380
                  logfile: redis_26380.log
                  pid_file: redis_26380.pid
                  port: 26380
            loglevel: notice
            maxmemory: 4gb
            maxmemory_policy: allkeys-lru
            package_subdir: realtime-new-doris/realtime/web_all/app/redis_26480
            tcp_keepalive: 300
            timeout: 0
            version: 6.2.14
    scala:
        type: ""
        description: 安装Scala（大数据节点）
        id_field: ""
        id_format: ""
        vars:
            install_dir: /data/scala
            package_subdir: realtime-new-doris/realtime/kafka
            version: 2.11.6
    server_init:
        type: global
        description: 服务器初始化（所有节点）
        id_field: ""
        id_format: ""
        vars:
            kernelModules:
                - ip_vs
                - ip_vs_rr
                - ip_vs_wrr
                - ip_vs_sh
                - nf_conntrack
                - br_netfilter
            limitsSettings:
                '* hard memlock': unlimited
                '* hard nofile': "102400"
                '* hard nproc': "102400"
                '* soft memlock': unlimited
                '* soft nofile': "102400"
                '* soft nproc': "102400"
                root hard nproc: unlimited
                root soft nproc: unlimited
            sysctlSettings:
                fs.file-max: 6.55356e+06
                net.core.somaxconn: 65536
                net.ipv4.ip_forward: 1
                net.ipv4.tcp_max_syn_backlog: 8192
                vm.dirty_background_ratio: 5
                vm.max_map_count: 2e+06
                vm.panic_on_oom: 0
                vm.swappiness: 0
    spark3:
        type: ""
        description: Spark3 分布式计算框架
        id_field: ""
        id_format: ""
        vars:
            adaptive_execution: "true"
            driver_memory: 2g
            dynamic_allocation: "false"
            event_log_subdir: spark/eventlog
            executor_cores: "2"
            executor_memory: 4g
            hadoop_conf_dir: '{{ .Global.install_base_dir }}/hadoop3/etc/hadoop'
            hadoop_home: '{{ .Global.install_base_dir }}/hadoop3'
            hadoop_version: 3.3.6
            hdfs_init_node: dw-master1
            install_subdir: spark
            log_subdir: spark/logs
            master_port: "7077"
            master_webui_port: "8080"
            max_executors: "10"
            min_executors: "1"
            package_subdir: spark-3.3.1-bin-hadoop3.3
            role: '{{ .Instance.ServiceName | split "/" | last }}'
            scala_home: ""
            shuffle_partitions: "200"
            spark_eventlog_dir: hdfs://{{ .Instance.Node.Hostname }}:9000/sparklogs
            spark_master_addr: '{{ .Instance.Node.Hostname }}'
            spark_yarn_jars: hdfs://{{ .Instance.Node.Hostname }}:9000/spark3jars/spark-3.3.1/jars/*
            version: 3.3.1
            worker_cores: "4"
            worker_memory: 8g
            worker_port: "7078"
            worker_webui_port: "8081"
    ssdb:
        type: ""
        description: SSDB高性能存储（编译安装，多实例）
        id_field: ""
        id_format: ""
        vars:
            bind: 0.0.0.0
            block_size: 32
            cache_size: 1024
            compaction_speed: 1000
            compression: "no"
            install_dir: /usr/local/ssdb
            instances:
                - config_file: ssdb_8892.conf
                  data_subdir: data2
                  port: 8892
                - config_file: ssdb_8893.conf
                  data_subdir: data3
                  port: 8893
                - config_file: ssdb_8894.conf
                  data_subdir: data4
                  port: 8894
                - config_file: ssdb_8895.conf
                  data_subdir: data5
                  port: 8895
                - config_file: ssdb_8897.conf
                  data_subdir: data7
                  port: 8897
                - config_file: ssdb_8898.conf
                  data_subdir: data8
                  port: 8898
            package_subdir: realtime-new-doris/realtime/web_all/etl-ssdb
            version: ssdb_master
            work_rps: 1000
            work_threads: 8
            write_buffer_size: 64
    zookeeper:
        type: ""
        description: ""
        id_field: myid
        id_format: index+1
        vars:
            client_port: 2181
            election_port: 3888
            init_limit: 10
            server_port: 2888
            sync_limit: 5
            tick_time: 2000
            version: 3.8.3
nodeOverrides: {}
