---
- name: Init hadoop-hdfs-zkfc
  shell: "yes | /data/hadoop3/bin/hdfs zkfc -formatZK"
  when: inventory_hostname == groups["hadoop3_zkfc"][0]

- name: Start ZKFC Service
  become: yes
  become_user: appoper
  shell: |
    nohup {{ install_dir }}/bin/hdfs --daemon start zkfc > /dev/null 2>&1 &
    sleep 5
  args:
    executable: /bin/bash
  when: inventory_hostname in groups["hadoop3_namenode"]

- name: Start JournalNode as persistent daemon
  shell: |
    nohup {{ install_dir }}/bin/hdfs --daemon start journalnode > /dev/null 2>&1 &
    sleep 5
  args:
    executable: /bin/bash
  when: inventory_hostname in groups['hadoop3']

- name: Format HDFS NameNode Master
  shell: |
    source {{ install_dir }}/etc/hadoop/hadoop-env.sh
    yes | {{ install_dir }}/bin/hdfs namenode -format
  when: inventory_hostname == groups["hadoop3_namenode"][0]
  args:
    executable: /bin/bash

- name: Start NameNode Service - Master
  shell: |
    nohup {{ install_dir }}/bin/hdfs --daemon start namenode > /dev/null 2>&1 &
    sleep 5
  args:
    executable: /bin/bash
  when: inventory_hostname == groups["hadoop3_namenode"][0]

- name: Format NameNode Standby
  shell: "/data/hadoop3/bin/hdfs namenode -bootstrapStandby"
  when: inventory_hostname == groups["hadoop3_namenode"][1]

- name: Start NameNode Service - Standby
  shell: |
    nohup {{ install_dir }}/bin/hdfs --daemon start namenode > /dev/null 2>&1 &
    sleep 5
  args:
    executable: /bin/bash
  when: inventory_hostname == groups["hadoop3_namenode"][1]

- name: Start Datanode
  shell: |
    nohup {{ install_dir }}/bin/hdfs --daemon start datanode > /dev/null 2>&1 &
    sleep 5
  args:
    executable: /bin/bash
  when: inventory_hostname in groups['hadoop3']

- name: Start resourcemanager
  shell: |
    nohup {{ install_dir }}/bin/hdfs --daemon start resourcemanager > /dev/null 2>&1 &
    sleep 5
  args:
    executable: /bin/bash
  when: inventory_hostname in groups['hadoop3']

- name: Start nodemanager
  shell: |
    nohup {{ install_dir }}/bin/hdfs --daemon start nodemanager > /dev/null 2>&1 &
    sleep 5
  args:
    executable: /bin/bash
  when: inventory_hostname in groups['hadoop3']

#- name: hadoop Password free login
#  debug:
#    msg: "hadoop启动所有组件的脚本，需要满足raeltiem-dw1免密登录其他节点，否则下面脚本执行失败"

#- name: Start Hadoop3 All OtherService
#  shell: "source /etc/profile && /bin/bash {{ install_dir }}/sbin/start-all.sh"
#  when: inventory_hostname == groups["hadoop3_namenode"][0]
